import type { ColorPalette } from '@park-ui/panda-preset';

/**
 * Axionic warm-gray neutral scale (sand-toned).
 *
 * Park UI's `createPreset()` automatically:
 * 1. Registers base tokens under `colors.gray.light.*` / `colors.gray.dark.*`
 * 2. Standardizes semantic token references from `colors.sand.*` to `colors.gray.*`
 * 3. Places semantic tokens under `semanticTokens.colors.gray`
 *
 * So `name` stays `'sand'` and references use `{colors.sand.light.*}` --
 * the standardizer rewrites them to `{colors.gray.light.*}` at config time.
 */
export const axionicSand: ColorPalette = {
	name: 'sand',
	tokens: {
		light: {
			'1': { value: '#fdfdfc' },
			'2': { value: '#f9f9f8' },
			'3': { value: '#f1f0ef' },
			'4': { value: '#e9e8e6' },
			'5': { value: '#e2e1de' },
			'6': { value: '#d9d8d5' },
			'7': { value: '#cfceca' },
			'8': { value: '#bcbbb5' },
			'9': { value: '#8d8d86' },
			'10': { value: '#82827c' },
			'11': { value: '#63635e' },
			'12': { value: '#21201c' },
			a1: { value: 'rgba(85, 85, 0, 0.01)' },
			a2: { value: 'rgba(85, 85, 0, 0.03)' },
			a3: { value: 'rgba(75, 65, 0, 0.06)' },
			a4: { value: 'rgba(65, 55, 0, 0.10)' },
			a5: { value: 'rgba(60, 50, 0, 0.13)' },
			a6: { value: 'rgba(55, 45, 0, 0.17)' },
			a7: { value: 'rgba(50, 40, 0, 0.21)' },
			a8: { value: 'rgba(45, 40, 0, 0.29)' },
			a9: { value: 'rgba(30, 30, 0, 0.48)' },
			a10: { value: 'rgba(25, 25, 0, 0.51)' },
			a11: { value: 'rgba(15, 15, 0, 0.63)' },
			a12: { value: 'rgba(5, 5, 0, 0.89)' },
		},
		dark: {
			'1': { value: '#111110' },
			'2': { value: '#191918' },
			'3': { value: '#222221' },
			'4': { value: '#2a2a28' },
			'5': { value: '#31312e' },
			'6': { value: '#3b3b37' },
			'7': { value: '#494844' },
			'8': { value: '#62625b' },
			'9': { value: '#6f6f68' },
			'10': { value: '#7c7c74' },
			'11': { value: '#b5b5ad' },
			'12': { value: '#eeeeec' },
			a1: { value: 'rgba(0, 0, 0, 0)' },
			a2: { value: 'rgba(245, 245, 200, 0.04)' },
			a3: { value: 'rgba(235, 235, 195, 0.08)' },
			a4: { value: 'rgba(230, 230, 175, 0.11)' },
			a5: { value: 'rgba(225, 225, 170, 0.14)' },
			a6: { value: 'rgba(220, 220, 165, 0.18)' },
			a7: { value: 'rgba(215, 215, 160, 0.24)' },
			a8: { value: 'rgba(210, 210, 155, 0.34)' },
			a9: { value: 'rgba(210, 210, 165, 0.39)' },
			a10: { value: 'rgba(210, 210, 170, 0.44)' },
			a11: { value: 'rgba(230, 230, 200, 0.68)' },
			a12: { value: 'rgba(250, 250, 240, 0.93)' },
		},
	},
	semanticTokens: {
		'1': { value: { _light: '{colors.sand.light.1}', _dark: '{colors.sand.dark.1}' } },
		'2': { value: { _light: '{colors.sand.light.2}', _dark: '{colors.sand.dark.2}' } },
		'3': { value: { _light: '{colors.sand.light.3}', _dark: '{colors.sand.dark.3}' } },
		'4': { value: { _light: '{colors.sand.light.4}', _dark: '{colors.sand.dark.4}' } },
		'5': { value: { _light: '{colors.sand.light.5}', _dark: '{colors.sand.dark.5}' } },
		'6': { value: { _light: '{colors.sand.light.6}', _dark: '{colors.sand.dark.6}' } },
		'7': { value: { _light: '{colors.sand.light.7}', _dark: '{colors.sand.dark.7}' } },
		'8': { value: { _light: '{colors.sand.light.8}', _dark: '{colors.sand.dark.8}' } },
		'9': { value: { _light: '{colors.sand.light.9}', _dark: '{colors.sand.dark.9}' } },
		'10': { value: { _light: '{colors.sand.light.10}', _dark: '{colors.sand.dark.10}' } },
		'11': { value: { _light: '{colors.sand.light.11}', _dark: '{colors.sand.dark.11}' } },
		'12': { value: { _light: '{colors.sand.light.12}', _dark: '{colors.sand.dark.12}' } },
		a1: { value: { _light: '{colors.sand.light.a1}', _dark: '{colors.sand.dark.a1}' } },
		a2: { value: { _light: '{colors.sand.light.a2}', _dark: '{colors.sand.dark.a2}' } },
		a3: { value: { _light: '{colors.sand.light.a3}', _dark: '{colors.sand.dark.a3}' } },
		a4: { value: { _light: '{colors.sand.light.a4}', _dark: '{colors.sand.dark.a4}' } },
		a5: { value: { _light: '{colors.sand.light.a5}', _dark: '{colors.sand.dark.a5}' } },
		a6: { value: { _light: '{colors.sand.light.a6}', _dark: '{colors.sand.dark.a6}' } },
		a7: { value: { _light: '{colors.sand.light.a7}', _dark: '{colors.sand.dark.a7}' } },
		a8: { value: { _light: '{colors.sand.light.a8}', _dark: '{colors.sand.dark.a8}' } },
		a9: { value: { _light: '{colors.sand.light.a9}', _dark: '{colors.sand.dark.a9}' } },
		a10: { value: { _light: '{colors.sand.light.a10}', _dark: '{colors.sand.dark.a10}' } },
		a11: { value: { _light: '{colors.sand.light.a11}', _dark: '{colors.sand.dark.a11}' } },
		a12: { value: { _light: '{colors.sand.light.a12}', _dark: '{colors.sand.dark.a12}' } },
		default: { value: { _light: '{colors.sand.light.9}', _dark: '{colors.sand.dark.9}' } },
		emphasized: { value: { _light: '{colors.sand.light.10}', _dark: '{colors.sand.dark.10}' } },
		fg: { value: { _light: 'white', _dark: 'white' } },
		text: { value: { _light: '{colors.sand.light.12}', _dark: '{colors.sand.dark.12}' } },
	},
};
