import { defineSlotRecipe } from '@pandacss/dev';

export const helpPanel = defineSlotRecipe({
	className: 'help-panel',
	slots: ['root', 'header', 'headerIcon', 'tabBar', 'tab', 'content', 'footer', 'accentBar'],
	base: {
		root: {
			position: 'absolute',
			top: '0',
			right: '0',
			zIndex: 40,
			h: 'full',
			w: '96',
			bg: 'bg.default',
			borderLeftWidth: '1px',
			borderColor: 'border.default',
			display: 'flex',
			flexDirection: 'column',
			boxShadow: '2xl',
			overflow: 'hidden',
			animation: 'slide-in-right 200ms ease-out',
		},
		header: {
			position: 'relative',
			px: '4',
			py: '3',
			borderBottomWidth: '1px',
			borderColor: 'border.default',
			bg: 'bg.default',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'space-between',
		},
		headerIcon: {
			w: '8',
			h: '8',
			borderRadius: 'l2',
			bg: 'colorPalette.a3',
			borderWidth: '1px',
			borderColor: 'colorPalette.8',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'center',
			color: 'colorPalette.11',
		},
		tabBar: {
			px: '2',
			py: '2',
			bg: 'bg.default',
			borderBottomWidth: '1px',
			borderColor: 'border.default/50',
			display: 'flex',
			flexWrap: 'wrap',
			gap: '1',
		},
		tab: {
			display: 'flex',
			alignItems: 'center',
			gap: '1.5',
			px: '2.5',
			py: '1.5',
			borderRadius: 'l2',
			fontSize: 'xs',
			fontWeight: 'medium',
			transition: 'all',
			borderWidth: '1px',
			cursor: 'pointer',
			color: 'fg.subtle',
			borderColor: 'transparent',
			_hover: {
				color: 'fg.default',
				bg: 'bg.emphasized',
			},
			'&[data-selected]': {
				bg: 'colorPalette.a3',
				color: 'colorPalette.11',
				borderColor: 'colorPalette.8',
			},
		},
		content: {
			flex: '1',
			overflowY: 'auto',
		},
		footer: {
			position: 'relative',
			px: '4',
			py: '2.5',
			borderTopWidth: '1px',
			borderColor: 'border.default',
			bg: 'bg.default',
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'space-between',
			fontSize: 'xs',
			color: 'fg.subtle',
		},
		accentBar: {
			position: 'absolute',
			insetInline: '0',
			h: '0.5',
			bgGradient: 'to-r',
			gradientFrom: 'colorPalette.7',
			gradientVia: 'colorPalette.9',
			gradientTo: 'colorPalette.11',
		},
	},
});
